name: 😮‍💨

on:
  push:
    branches:
      - main
    paths:
      - "**.go"
  workflow_dispatch:

jobs:
  buildl:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
          fetch-depth: 0
      - name: Pre-Cleanup
        run: |
          rm backup *.deb
      - name: set up go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.17.7'
          check-latest: true
      - name: get dependencies
        run : |
          go get github.com/goreleaser/nfpm/v2/cmd/nfpm@latest
          go install github.com/goreleaser/nfpm/v2/cmd/nfpm
          go get github.com/joshhhhyyyy/increment
          go install github.com/joshhhhyyyy/increment
      - name: Build
        run: |
          go mod tidy
          go build backup.go
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true
          git_tag_gpgsign: true
          git_push_gpgsign: false
      - name: set up git
        run: |
          git config --global gpg.program gpg2
      - name: increment + commit
        env:
          key: ${{ secrets.SENTRYKEY }}
        run: |
          increment --nfpm
